version: "3.8"
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    working_dir: /src
    ports:
      - 3000:3000
    volumes:
      - ./src:/src
    tty: true
    restart: always
    command: bash -c "npm run start"
  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    env_file:
      - src/.env.local
    restart: always
  nginx:
    image: nginx:1.25.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/dist:/dist
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
  certbot:
    image: certbot/certbot:v2.8.0
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/dist:/dist
    command: ["--version"]

volumes:
  db-store: