version: '3.8' 
services:                      
  node:
    image: node:latest
    working_dir: /src
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
      - 6006:6006
    volumes:
      - ./src:/src
    command: sh -c 'npm run dev'
    tty: true
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    env_file:
      - src/.env.local

volumes:
  db-store: