version: "3.8"
services:
  node:
    image: node:latest
    working_dir: /src
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./src:/src
    command: bash
    tty: true
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    env_file:
      - src/.env.local
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
  certbot:
    image: certbot/certbot:v2.8.0
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    command: ["--version"]

volumes:
  db-store:
